name: Release to npm & GitHub

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Version bump type"
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write   # needed to push commits/tags & create releases

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # so the tag push and release notes work well

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: npm ci

      # Optional: build your package (uncomment if you have a build step)
      # - name: Build
      #   run: npm run build

      - name: Bump version (creates commit + tag)
        id: bump
        run: |
          npm version ${{ inputs.bump }} -m "chore(release): %s [skip ci]"
          echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Push commit and tag
        run: |
          git push origin HEAD
          git push origin ${{ steps.bump.outputs.tag }}

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # If your package is public, keep --access public
          # For scoped private packages, remove --access
          npm publish --access public

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump.outputs.tag }}
          generate_release_notes: true
